/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author luans
 */
public class JFPaginaInicialFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JFPaginaInicialFuncionario
     */
    public JFPaginaInicialFuncionario() {
        initComponents();
                this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFotoEquipe = new javax.swing.JLabel();
        lblIcone = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        lblJargao = new javax.swing.JLabel();
        lblFuncionarios = new javax.swing.JLabel();
        lblNovoFuncionarios = new javax.swing.JLabel();
        lblNovoProduto = new javax.swing.JLabel();
        BarraNavegacao = new javax.swing.JMenuBar();
        menuLoja = new javax.swing.JMenu();
        Promos = new javax.swing.JMenuItem();
        lojaGeral = new javax.swing.JMenuItem();
        MenuFuncionários = new javax.swing.JMenu();
        NovoFuncionario = new javax.swing.JMenuItem();
        Funcionarios = new javax.swing.JMenuItem();
        MenuProdutos = new javax.swing.JMenu();
        CadastrarProduto = new javax.swing.JMenuItem();
        Produto = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();
        CadastrarCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(93, 172, 189));

        lblFotoEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employees.jpg"))); // NOI18N

        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aromayIcon.png"))); // NOI18N

        lblProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cream.png"))); // NOI18N
        lblProdutos.setText("PRODUTOS");
        lblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdutosMouseClicked(evt);
            }
        });

        lblJargao.setBackground(new java.awt.Color(93, 172, 189));
        lblJargao.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        lblJargao.setText("VOCÊ NOS FAZ EXISTIR.");

        lblFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/business.png"))); // NOI18N
        lblFuncionarios.setText("FUNCIONÁRIOS");
        lblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncionariosMouseClicked(evt);
            }
        });

        lblNovoFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man.png"))); // NOI18N
        lblNovoFuncionarios.setText("NOVO FUNCIONÁRIO");
        lblNovoFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovoFuncionariosMouseClicked(evt);
            }
        });

        lblNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop.png"))); // NOI18N
        lblNovoProduto.setText("NOVO PRODUTO");
        lblNovoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovoProdutoMouseClicked(evt);
            }
        });

        menuLoja.setText("Loja");

        Promos.setText("Promoções - Página Inicial");
        Promos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromosActionPerformed(evt);
            }
        });
        menuLoja.add(Promos);

        lojaGeral.setText("Loja - geral");
        lojaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojaGeralActionPerformed(evt);
            }
        });
        menuLoja.add(lojaGeral);

        BarraNavegacao.add(menuLoja);

        MenuFuncionários.setText("Funcionários");

        NovoFuncionario.setText("Cadastrar funcionários");
        NovoFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovoFuncionarioMouseClicked(evt);
            }
        });
        NovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoFuncionarioActionPerformed(evt);
            }
        });
        MenuFuncionários.add(NovoFuncionario);

        Funcionarios.setText("Funcionários");
        Funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuncionariosMouseClicked(evt);
            }
        });
        Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionariosActionPerformed(evt);
            }
        });
        MenuFuncionários.add(Funcionarios);

        BarraNavegacao.add(MenuFuncionários);

        MenuProdutos.setText("Produtos");

        CadastrarProduto.setText("Cadastrar Produto");
        CadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarProdutoMouseClicked(evt);
            }
        });
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });
        MenuProdutos.add(CadastrarProduto);

        Produto.setText("Produtos cadastrados");
        Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutoMouseClicked(evt);
            }
        });
        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        MenuProdutos.add(Produto);

        BarraNavegacao.add(MenuProdutos);

        MenuClientes.setText("Clientes");

        Clientes.setText("Clientes cadastrados");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        MenuClientes.add(Clientes);

        CadastrarCliente.setText("Cadastrar Cliente");
        MenuClientes.add(CadastrarCliente);

        BarraNavegacao.add(MenuClientes);

        setJMenuBar(BarraNavegacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblNovoProduto)
                        .addGap(29, 29, 29)
                        .addComponent(lblProdutos)
                        .addGap(27, 27, 27)
                        .addComponent(lblFuncionarios)
                        .addGap(34, 34, 34)
                        .addComponent(lblNovoFuncionarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFotoEquipe)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIcone)
                                .addGap(18, 18, 18)
                                .addComponent(lblJargao, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFotoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJargao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoFuncionarios)
                    .addComponent(lblFuncionarios)
                    .addComponent(lblProdutos)
                    .addComponent(lblNovoProduto))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoFuncionarioActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFCadFunc fun = new JFCadFunc();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NovoFuncionarioActionPerformed

    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoActionPerformed

    private void lblNovoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoProdutoMouseClicked
        // TODO add your handling code here:
        JFManterProdutos produto = new JFManterProdutos();
        produto.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblNovoProdutoMouseClicked

    private void CadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarProdutoMouseClicked
        // TODO add your handling code here:
        JFCadastroProd produto = new JFCadastroProd();
        produto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadastrarProdutoMouseClicked

    private void ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ProdutoMouseClicked

    private void NovoFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoFuncionarioMouseClicked
        // TODO add your handling code here:
        JFCadFunc fun = new JFCadFunc();
        fun.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_NovoFuncionarioMouseClicked

    private void FuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuncionariosMouseClicked
        // TODO add your handling code here:
        JFManterFuncionarios fun = new JFManterFuncionarios();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FuncionariosMouseClicked

    private void lblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutosMouseClicked
        // TODO add your handling code here:
        JFManterProdutos produto = new JFManterProdutos();
        produto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblProdutosMouseClicked

    private void lblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionariosMouseClicked
        // TODO add your handling code here:
        JFManterFuncionarios fun = new JFManterFuncionarios();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFuncionariosMouseClicked

    private void lblNovoFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoFuncionariosMouseClicked


    }//GEN-LAST:event_lblNovoFuncionariosMouseClicked

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesActionPerformed

    private void FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionariosActionPerformed
        // TODO add your handling code here:
        JFManterFuncionarios fun = new JFManterFuncionarios();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FuncionariosActionPerformed

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
        // TODO add your handling code here:
        JFCadastroProd produto = new JFCadastroProd();
        produto.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    private void PromosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromosActionPerformed
        // TODO add your handling code here:
        JFPaginaInicial pgi = new JFPaginaInicial();
        pgi.setVisible(true);

    }//GEN-LAST:event_PromosActionPerformed

    private void lojaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojaGeralActionPerformed
        // TODO add your handling code here:
        JFLoja lj = new JFLoja();
        lj.setVisible(true);
    }//GEN-LAST:event_lojaGeralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPaginaInicialFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPaginaInicialFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPaginaInicialFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPaginaInicialFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPaginaInicialFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraNavegacao;
    private javax.swing.JMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CadastrarProduto;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Funcionarios;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuFuncionários;
    private javax.swing.JMenu MenuProdutos;
    private javax.swing.JMenuItem NovoFuncionario;
    private javax.swing.JMenuItem Produto;
    private javax.swing.JMenuItem Promos;
    private javax.swing.JLabel lblFotoEquipe;
    private javax.swing.JLabel lblFuncionarios;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JLabel lblJargao;
    private javax.swing.JLabel lblNovoFuncionarios;
    private javax.swing.JLabel lblNovoProduto;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JMenuItem lojaGeral;
    private javax.swing.JMenu menuLoja;
    // End of variables declaration//GEN-END:variables
}
